#pragma config(Motor,  motorA,          motor,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[Motor] = 100;
	wait1Msec(1000);
	motor[Motor] = 0;
}
